### ISSUE TITLE
Can't add new component

### ISSUE THREAD

**Issue by EwaMakowska** [abenz1267/LitElement-TypeScript-and-Webpack-Example#7]
I try to add really simply, new element:

src/components/chessboard.ts
```
import { LitElement, html, customElement, property } from "lit-element";

export class Chessboadr extends LitElement {

    render() {
        return html `
            <div id='chessboard'>test</div>
      `;
    }
}
```

src/index.ts
```
import '../style.css';

import './components/chessboard';
import './components/old/button';
import './components/old/infobox';
```

src/index.html
```
...
<body>
    <chessboadr></chessboadr>
  <action-button foo="bar"></action-button>
  <text-box id="info" content="Hello"></text-box>
</body>
...
```

and my new chessboard component is not visible. What am I doing wrong? How to add new component? I have no error in console.

**Comment by abenz1267** [comment]
Hello, 

please read the official LitElement guide over at https://lit-element.polymer-project.org/guide.

You need to define your new custom component via an annotation: `@customElement('my-element')`


Regards
